- name: download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: unzip wordpress
  shell: tar xfvz /tmp/latest.tar.gz -C /vagrant/  --owner vagrant --group vagrant --no-same-owner

- name: remove packed wordpress
  shell: rm /tmp/latest.tar.gz

- name: create database
  mysql_db: name=wordpress state=present login_user=root login_password={{ mysql.root_password }}

- name: add nginx site
  become: yes
  template: src=wordpress.tpl dest=/etc/nginx/sites-enabled/wordpress
  notify: restart nginx